Repository sb3-monew-team1/sb03-monew-team1, pull requests merged in 2025-07, with the labels that each got.

#10 [MN-39] feat: 패키지 구조 설계 및 초기 설정
  package-lock.json
  src/main/java/com/sprint/mission/sb03monewteam1/config/Config.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/Controller.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/ControllerApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/TransferDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/request/RequestDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/response/ResponseDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Article.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Comment.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Interest.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Notification.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/User.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/UserActivity.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/base/BaseEntity.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/base/BaseUpdatableEntity.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/Exception.java
  src/main/java/com/sprint/mission/sb03monewteam1/logging/Logging.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/Mapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/Repository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/Service.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/storage/Storage.java
  src/main/java/com/sprint/mission/sb03monewteam1/util/Util.java
Labels: DevOps

#28 [feat] [MN-13] RSS / Naver API 수집 모듈
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/java/com/sprint/mission/sb03monewteam1/collector/NewsCollector.java
  src/main/java/com/sprint/mission/sb03monewteam1/config/BatchConfig.java
  src/main/java/com/sprint/mission/sb03monewteam1/config/WebClientConfig.java
  src/main/resources/application.yaml
  src/test/java/com/sprint/mission/sb03monewteam1/Sb03MonewTeam1ApplicationTests.java
  src/test/java/com/sprint/mission/sb03monewteam1/collector/NewsCollectorTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/config/TestEnvSetup.java
  src/test/java/com/sprint/mission/sb03monewteam1/config/WebClientConfigTest.java
Labels: feature

#31 [feat] [MN-20] 관심사 등록 API
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/close-jira-issue.yml
  build.gradle
  src/main/java/com/sprint/mission/sb03monewteam1/controller/InterestController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/InterestApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/InterestDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/request/InterestRegisterRequest.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/response/InterestResponse.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Interest.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/InterestKeyword.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/ErrorCode.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/interest/InterestDuplicateException.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/interest/InterestException.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/interest/InterestSimilarityException.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/InterestMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/InterestKeywordRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/InterestRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestServiceImpl.java
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-Bko75Eiv.js
  src/main/resources/static/assets/index-D30UMZL2.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
  src/test/java/com/sprint/mission/sb03monewteam1/controller/InterestControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/InterestFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/InterestIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/InterestServiceTest.java
Labels: feature

#32 [feat] [MN-9] 댓글 등록 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/CommentController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/CommentApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/CommentDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/request/CommentRegisterRequest.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Article.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/ArticleView.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Comment.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/ErrorCode.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/comment/CommentException.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/CommentMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/ArticleRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/CommentRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/UserRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/CommentControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/ArticleFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/CommentFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/CommentServiceTest.java
Labels: feature

#35 [feat] [MN-18] 기사 뷰 등록/뉴스 기사 목록 조회
  build.gradle
  src/main/java/com/sprint/mission/sb03monewteam1/config/QueryDslConfig.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/ArticleController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/ArticleApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/ArticleDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/ArticleViewDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/response/CursorPageResponseArticleDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Article.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/ArticleView.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Comment.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/ErrorCode.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/article/ArticleException.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/article/ArticleNotFoundException.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/article/DuplicateArticleViewException.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/article/InvalidCursorException.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/ArticleMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/ArticleViewMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/ArticleRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/ArticleRepositoryCustom.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/ArticleRepositoryImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/ArticleViewRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/com/sprint/mission/sb03monewteam1/controller/ArticleControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/ArticleViewFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/ArticleIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceTest.java
Labels: feature

#47 [chore] [MN-54] 중간 엔티티 및 레포지토리 생성
  src/main/java/com/sprint/mission/sb03monewteam1/entity/ArticleInterest.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/CommentLike.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Subscription.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/ArticleInterestRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/CommentLikeRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/SubscriptionRepository.java
Labels: config

#49 [feat] [MN-10] 댓글 수정 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/CommentController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/CommentApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/request/CommentUpdateRequest.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/ErrorCode.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/comment/CommentNotFoundException.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/comment/UnauthorizedCommentAccessException.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/CommentControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/CommentFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/CommentServiceTest.java
Labels: feature

#54 [feat] [MN-23] 관심사 조회 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/InterestController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/InterestApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/InterestDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/request/InterestRegisterRequest.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/response/InterestResponse.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/InterestMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/InterestRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/InterestRepositoryCustom.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/InterestRepositoryImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/InterestDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/InterestControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/InterestFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/InterestIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/InterestServiceTest.java
Labels: feature

#56 [feat] [MN-12] 댓글 논리 삭제 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/CommentController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/CommentApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Comment.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/CommentControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/ArticleFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/CommentFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/repository/CommentRepositoryTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/CommentServiceTest.java
Labels: feature

#64 [feat] [MN-58] 댓글 논리 삭제 조회 방식 커스텀 쿼리로 변경
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Comment.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/CommentRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/CommentRepositoryImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/UserRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/repository/CommentRepositoryTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/CommentServiceTest.java
Labels: feature

#58 [feat] [MN-52] 뉴스 수집 추가 작업
  src/main/java/com/sprint/mission/sb03monewteam1/batch/job/ArticleCollectJobConfig.java
  src/main/java/com/sprint/mission/sb03monewteam1/collector/HankyungNewsCollector.java
  src/main/java/com/sprint/mission/sb03monewteam1/collector/NaverNewsCollector.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/ArticleController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/ArticleApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/response/CursorPageResponseArticleDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/ErrorCode.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/article/ArticleCollectException.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/article/ArticleParseException.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/InterestKeywordRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/scheduler/ArticleBackupScheduler.java
  src/main/java/com/sprint/mission/sb03monewteam1/scheduler/ArticleCollectScheduler.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceImpl.java
  src/main/resources/log4j2-spring.xml
  src/test/java/com/sprint/mission/sb03monewteam1/batch/job/ArticleBackupJobTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/batch/job/ArticleCollectJobTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/ArticleControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/ArticleIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/scheduler/ArticleCollectSchedulerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceTest.java
  src/test/resources/log4j2-test.xml
Labels: feature

#65 [feat] [MN-14] 댓글 물리 삭제 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/CommentController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/CommentApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/CommentLikeRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/CommentControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/CommentServiceTest.java
Labels: feature

#68 [feat] [MN-25] 관심사 구독 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/InterestController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/InterestApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/InterestDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/SubscriptionDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/interest/InterestException.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/interest/InterestNotFoundException.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/interest/SubscriptionDuplicateException.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/SubscriptionMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/SubscriptionRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/InterestControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/InterestFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/InterestIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/InterestServiceTest.java
Labels: feature

#72 [feat] [MN-15] 댓글 좋아요 등록 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/CommentController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/CommentApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/CommentDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/CommentLikeDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Comment.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/ErrorCode.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/comment/CommentAlreadyLikedException.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/CommentLikeMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/CommentLikeRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/CommentRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/AllDataSeederRunner.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/ArticleDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/CommentDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/CommentLikeDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/CommentControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/CommentLikeFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/CommentServiceTest.java
Labels: feature

#74 [feat] [MN-60] 관심사 조회 시 구독 여부 체크 추가
  src/main/java/com/sprint/mission/sb03monewteam1/controller/InterestController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/InterestApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/InterestRepositoryImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/SubscriptionRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/AllDataSeederRunner.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/SubscriptionDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/InterestControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/InterestIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/InterestServiceTest.java
Labels: feature

#76 [feat] [MN-44] 뉴스 기사 물리 삭제
  src/main/java/com/sprint/mission/sb03monewteam1/controller/ArticleController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/ArticleApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Article.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/ArticleView.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/User.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/base/BaseEntity.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/ArticleInterestRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/ArticleViewRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/CommentRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/ArticleControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/ArticleFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/ArticleViewFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/CommentFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceTest.java
Labels: feature

#83 [feat][MN-16] 댓글 좋아요 취소 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/CommentController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/CommentApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/ErrorCode.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/comment/CommentLikeNotFoundException.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/CommentLikeRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/CommentControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/CommentServiceTest.java
Labels: feature

#81 [chore] [MN-57] Docker 환경 구성
  Dockerfile
  docker-compose.yml
  src/main/java/com/sprint/mission/sb03monewteam1/config/WebMvcConfig.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/ArticleController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/CommentController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/ArticleApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/CommentApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/AllDataSeederRunner.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/ArticleDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/CommentDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/CommentLikeDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/InterestDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/SubscriptionDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/UserDataSeeder.java
  src/main/resources/schema.sql
Labels: config

#87 [feat] [MN-63] 좋아요 알림 등록
  docker-compose.yml
  prometheus.yml
  src/main/java/com/sprint/mission/sb03monewteam1/Sb03MonewTeam1Application.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/CollectedArticleDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/NotificationDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/ResourceType.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Comment.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Notification.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/CommentLikeEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/NewArticleCollectEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/NotificationEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/ErrorCode.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/notification/NotificationException.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/notification/NotificationSendException.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/NotificationRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/SubscriptionRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/ArticleDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/seeder/CommentDataSeeder.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/NotificationService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/NotificationServiceImpl.java
  src/main/resources/docker-pg-init.sql
  src/test/java/com/sprint/mission/sb03monewteam1/event/NotificationEventListenerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/NotificationIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/CommentServiceTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/NotificationServiceTest.java
  src/test/resources/application-test.yaml
Labels: feature

#84 [feat] [MN-61] 논리 삭제된 댓글을 제외한 총 댓글 수 집계 로직 수정
  src/main/java/com/sprint/mission/sb03monewteam1/repository/CommentRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/CommentServiceTest.java
Labels: feature

#93 [test] [MN-62] 댓글 통합 테스트 코드 작성
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/CommentMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/CommentIntegrationTest.java
Labels: feature

#95 [feat] [MN-31] 개별 알림 확인 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/NotificationController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/NotificationApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/NotificationDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/ErrorCode.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/notification/NotificationAccessDeniedException.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/notification/NotificationNotFoundException.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/NotificationMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/NotificationService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/NotificationServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/NotificationControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/NotificationFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/NotificationIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/NotificationServiceTest.java
Labels: feature

#97 [feat] [MN-32] 전체 알림 확인 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/NotificationController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/NotificationApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/jpa/notification/NotificationRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/jpa/user/UserRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/NotificationService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/NotificationServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/NotificationControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/NotificationIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/NotificationServiceTest.java
Labels: feature

#101 [feat] [MN-22] 관심사 삭제 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/InterestController.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Interest.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/InterestKeyword.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/jpa/interest/InterestKeywordRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/jpa/subscription/SubscriptionRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/InterestControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/InterestIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/InterestServiceTest.java
Labels: feature

#109 [fix] [MN-67] 알림 ResourceType 대문자로 수정
  src/main/java/com/sprint/mission/sb03monewteam1/dto/ResourceType.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/NotificationServiceImpl.java
  src/main/resources/application-postgres.yaml
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/NotificationFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/NotificationIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/NotificationServiceTest.java
Labels: bug

#106 [feat] [MN-33] 알림 삭제 (스케줄러 버전)
  src/main/java/com/sprint/mission/sb03monewteam1/controller/NotificationController.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/ErrorCode.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/notification/NotificationCleanupException.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/jpa/notification/NotificationRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/scheduler/NotificationCleanupScheduler.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/NotificationService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/NotificationServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/scheduler/NotificationCleanupSchedulerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/NotificationServiceTest.java
Labels: feature

#112 [feat] [MN-27] 사용자 활동 내역 조회
  .github/workflows/ci.yml
  build.gradle
  docker-compose.yml
  src/main/java/com/sprint/mission/sb03monewteam1/config/JpaConfig.java
  src/main/java/com/sprint/mission/sb03monewteam1/config/MongoConfig.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/UserActivityController.java
  src/main/java/com/sprint/mission/sb03monewteam1/document/ArticleViewActivity.java
  src/main/java/com/sprint/mission/sb03monewteam1/document/CommentActivity.java
  src/main/java/com/sprint/mission/sb03monewteam1/document/CommentLikeActivity.java
  src/main/java/com/sprint/mission/sb03monewteam1/document/SubscriptionActivity.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/ArticleViewActivityDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/CommentActivityDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/CommentLikeActivityDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/UserActivityDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/ArticleViewActivityCreateEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/CommentActivityCreateEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/CommentActivityDeleteEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/CommentActivityUpdateEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/CommentLikeActivityCreateEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/CommentLikeActivityDeleteEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/SubscriptionActivityCreateEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/SubscriptionActivityDeleteEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/AbstractActivityEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/ArticleViewActivityEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/CommentActivityEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/CommentLikeActivityEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/SubscriptionActivityEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/ArticleViewActivityMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/CommentActivityMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/CommentLikeActivityMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/jpa/interest/InterestKeywordRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/jpa/interest/InterestRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/mongodb/ArticleViewActivityRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/mongodb/CommentActivityRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/mongodb/CommentLikeActivityRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/mongodb/SubscriptionActivityRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/UserActivityService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/UserActivityServiceImpl.java
  src/main/resources/docker-mongo-init.js
  src/test/java/com/sprint/mission/sb03monewteam1/Sb03MonewTeam1ApplicationTests.java
  src/test/java/com/sprint/mission/sb03monewteam1/config/LoadTestEnv.java
  src/test/java/com/sprint/mission/sb03monewteam1/config/MongoContainerInitializer.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/UserActivityControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/UserActivityIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/CommentServiceTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/InterestServiceTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/UserActivityServiceTest.java
Labels: feature

#115 [feat] [MN-66] 스프링 배치 구현 (알림 삭제)
  src/main/java/com/sprint/mission/sb03monewteam1/batch/job/NotificationDeleteJobConfig.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/jpa/notification/NotificationRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/scheduler/NotificationCleanupScheduler.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/main/resources/schema.sql
  src/test/java/com/sprint/mission/sb03monewteam1/config/TestConfig.java
  src/test/java/com/sprint/mission/sb03monewteam1/scheduler/NotificationCleanupSchedulerTest.java
Labels: feature

#118 [feat] [MN-49] 관심사 구독 취소 API
  src/main/java/com/sprint/mission/sb03monewteam1/controller/InterestController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/InterestApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/ErrorCode.java
  src/main/java/com/sprint/mission/sb03monewteam1/exception/interest/SubscriptionNotFoundException.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/jpa/subscription/SubscriptionRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/InterestControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/InterestIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/InterestServiceTest.java
Labels: feature

#119 [feat] [MN-46] 로그 메시지 및 응답 헤더 관리
  src/main/java/com/sprint/mission/sb03monewteam1/batch/job/LogBackupJobConfig.java
  src/main/java/com/sprint/mission/sb03monewteam1/scheduler/ArticleCollectScheduler.java
  src/main/java/com/sprint/mission/sb03monewteam1/scheduler/LogBackupScheduler.java
  src/main/resources/application.yaml
  src/test/java/com/sprint/mission/sb03monewteam1/batch/job/LogBackupJobConfigTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/scheduler/LogBackupSchedulerTest.java
Labels: config

#127 [feat] [MN-68] 뉴스 기사 추가 작업
  src/main/java/com/sprint/mission/sb03monewteam1/batch/job/ArticleCollectJobConfig.java
  src/main/java/com/sprint/mission/sb03monewteam1/collector/HankyungNewsCollector.java
  src/main/java/com/sprint/mission/sb03monewteam1/collector/NaverNewsCollector.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/ArticleController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/ArticleApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/dto/ArticleDto.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/NewsCollectJobCompletionListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/NotificationEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/ArticleMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/jpa/articleInterest/ArticleInterestRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/repository/jpa/articleView/ArticleViewRepository.java
  src/main/java/com/sprint/mission/sb03monewteam1/scheduler/ArticleCollectScheduler.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleService.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/InterestServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/UserServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/storage/Storage.java
  src/main/resources/application.yaml
  src/test/java/com/sprint/mission/sb03monewteam1/batch/job/ArticleCollectJobTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/ArticleControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/event/NotificationEventListenerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/fixture/ArticleFixture.java
  src/test/java/com/sprint/mission/sb03monewteam1/integration/NotificationIntegrationTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/scheduler/ArticleCollectSchedulerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceTest.java
Labels: bug

#135 [test] [MN-74] 댓글 관리_테스트 케이스 추가
  build.gradle
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/repository/CommentRepositoryTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/CommentServiceTest.java
Labels: refactoring

#141 [feat] [MN-76] 뉴스 기사 추가 작업
  grafana/provisioning/dashboards/json/New dashboard-1753252745228.json
  src/main/java/com/sprint/mission/sb03monewteam1/batch/job/ArticleBackupJobConfig.java
  src/main/java/com/sprint/mission/sb03monewteam1/batch/job/LogBackupJobConfig.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/ArticleController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/ArticleApi.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/Article.java
  src/main/java/com/sprint/mission/sb03monewteam1/entity/base/BaseEntity.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/NotificationEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/mapper/ArticleMapper.java
  src/main/java/com/sprint/mission/sb03monewteam1/scheduler/ArticleBackupScheduler.java
  src/main/java/com/sprint/mission/sb03monewteam1/scheduler/ArticleCollectScheduler.java
  src/main/java/com/sprint/mission/sb03monewteam1/scheduler/LogBackupScheduler.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/util/S3Util.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/test/java/com/sprint/mission/sb03monewteam1/batch/job/ArticleBackupJobTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/batch/job/ArticleCollectJobTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/batch/job/LogBackupJobConfigTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/controller/ArticleControllerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/scheduler/ArticleCollectSchedulerTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceTest.java
Labels: feature

#144 [refactor] [MN-83] 사용자 활동 내역 조회_로깅 개선 및 네이밍 통일
  src/main/java/com/sprint/mission/sb03monewteam1/event/ArticleViewCountActivityUpdateEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/CommentLikeActivityCreateEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/CommentLikeCountActivityUpdateEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/UserNameActivityUpdateEvent.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/ArticleViewActivityEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/CommentActivityEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/CommentLikeActivityEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/event/listener/SubscriptionActivityEventListener.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/CommentServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/UserActivityServiceImpl.java
  src/main/java/com/sprint/mission/sb03monewteam1/service/UserServiceImpl.java
  src/test/java/com/sprint/mission/sb03monewteam1/config/TestConfig.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/ArticleServiceTest.java
  src/test/java/com/sprint/mission/sb03monewteam1/service/UserServiceTest.java
Labels: refactoring

#147 [MN-41] chore: 배포 테스트 확인
  Dockerfile
  src/main/resources/application-postgres.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
Labels: config

#149 [MN-84] docs: UserActivityApi Swagger 문서 추가
  src/main/java/com/sprint/mission/sb03monewteam1/controller/UserActivityController.java
  src/main/java/com/sprint/mission/sb03monewteam1/controller/api/UserActivityApi.java
Labels: documentation
